name: Server-Helper
main: ServerHelper\ServerHelper
version: 2.4.2[b]
api:
- 2.0.0 #pmmp
- 3.0.0 #pmmp
- 3.0.1 #altay
- 3.0.5 #altay
- 3.0.7 #altay
- 3.2.5 #pmmp
- 4.0.0 #altay
author: PMExperts

#PMExperts
#TuranicTeam

commands:
  aboutsh:
    description: "about ServerHelper"
    usage: "/aboutsh"
  changelogsh:
    description: "changes of ServerHelper"
    usage: "/changelogsh"
  broadcast:
    description: "broadcast your message to all Players"
    aliases: [bc]
    usage: "/broadcast <message>"
  clear:
    desription: "clear inventory"
    aliases: [c]
    usage: "/clear <player>"
  cleararmor:
    description: "clear armor inventory"
    aliases: [ca]
    usage: "/cleararmor <player>"
  day:
    description: "set time to day"
    usage: "/day"
  night:
    description: "set time to night"
    usage: "/night"
  feed:
    description: "fed player"
    usage: "/feed <player>"
  fly:
    description: "enable fly for players"
    usage: "/fly <player>"
  gma:
    description: "set gamemode to adventure"
    usage: "/gma <player>"
  gmc:
    description: "set gamemode to creative"
    usage: "/gmc <player>"
  gms:
    description: "set gamemode to survival"
    usage: "/gms <player>"
  gmsp:
    description: "set gamemode to spectator"
    usage: "/gmsp <player>"
  heal:
    description: "heal player to max hearts"
    usage: "/heal <player>"
  itemid:
    description: "get item ID of item in your hand"
    usage: "/itemid"
  nickname:
    description: "changes players nickname"
    usage: "/nickname <player> <nickname>"
    aliases: [nick]
  test:
    description: "test players ping"
    usage: "/test"
  tstop:
    description: "stop time in your world"
    usage: "/tstop"
  shhelp:
    description: "get all commands of ServerHelper"
    aliases: [shh]
    usage: "/shhelp"
  vanish:
    description: "hide you from players"
    aliases: [v]
    usage: "/vanish <on/off> <player>"
  playersize:
    description: "change your skin size"
    aliases: [size]
    usage: "/playersize <player>"
  tphere:
    description: "teleport player to you"
    usage: "/tphere <player>"

permissions:
  serverhelper.*:
    default: op
    description: "Full access to ServerHelper"
    children:
      serverhelper.command.about:
        default: true
        description: "use about command"
      serverhelper.command.changelog:
        default: true
        description: "use changelog command"
      serverhelper.command.broadcast:
        default: op
        description: "broadcast command"
      serverhelper.command.clear:
        default: op
        description: "clear command"
      serverhelper.command.cleararmor:
        default: op
        description: "clear armor command"
      serverhelper.command.day:
        default: op
        description: "day command"
      serverhelper.command.night:
        default: op
        description: "night command"
      serverhelper.command.feed:
        default: op
        description: "feed command"
      serverhelper.command.fly:
        default: op
        description: "fly command"
      serverhelper.command.gmc:
        default: op
        description: "gmc command"
      serverhelper.command.gma:
        default: op
        description: "gma command"
      serverhelper.command.gms:
        default: op
        description: "gms command"
      serverhelper.command.gmsp:
        default: op
        description: "gmsp command"
      serverhelper.command.heal:
        default: op
        description: "heal command"
      serverhelper.command.itemid:
        default: op
        description: "itemid command"
      serverhelper.command.nickname:
        default: op
        description: "nickname command"
      serverhelper.command.test:
        default: true
        description: "test/ping command"
      serverhelper.command.tstop:
        default: op
        description: "tstop command"
      serverhelper.command.playersize:
        default: op
        description: "playersize command"
      serverhelper.command.vanish:
        default: op
        description: "vanish command"
      serverhelper.command.shhelp:
        default: true
        description: "serverhelper command list"
