#╔═══╗╔═╗╔═╗╔═══╗╔═╗╔═╗╔═══╗╔═══╗╔═══╗╔════╗╔═══╗
#║╔═╗║║║╚╝║║║╔══╝╚╗╚╝╔╝║╔═╗║║╔══╝║╔═╗║║╔╗╔╗║║╔═╗║
#║╚═╝║║╔╗╔╗║║╚══╗─╚╗╔╝─║╚═╝║║╚══╗║╚═╝║╚╝║║╚╝║╚══╗
#║╔══╝║║║║║║║╔══╝─╔╝╚╗─║╔══╝║╔══╝║╔╗╔╝──║║──╚══╗║
#║║───║║║║║║║╚══╗╔╝╔╗╚╗║║───║╚══╗║║║╚╗──║║──║╚═╝║
#╚╝───╚╝╚╝╚╝╚═══╝╚═╝╚═╝╚╝───╚═══╝╚╝╚═╝──╚╝──╚═══╝
#
#ServerHelper (c) 2018
#This Plugin is licensed under GNU General Public License v3.0, it is free to use.
#You can take some code out of our Plugin but please do not change the Author and Name.
#
#>----------------------------------------------------------------------------------------<
#
# Team: PMExpertsDE
# Author: HonorGamerHD
# Discord: https://discordapp.com/invite/Cnffuhs
# Website: http://pmexperts.tk


#PLEASE DO NOT CHANGE THIS!!!
VERSION: 2.4.2[b]

#Prefix of ServerHelper
#English: §7» §bSH §7»
PluginPrefix: "§7» §bSH §7» "

#Prefix of Broadcast Command
#Standard: §7» §l§bBroadcast §r§7»
BroadcastPrefix: "§7» §l§bBroadcast §r§7» "

#choose your Language here!
#Default: English
#Languages: English, Deutsch, Italiano | add more via pull request!
Language: English